cp higgsCombineTest.AsymptoticLimits.0Jet.mH125.root Combine/
cp higgsCombineTest.AsymptoticLimits.1Jet.mH125.root Combine/
cp higgsCombineTest.AsymptoticLimits.2JetGG.mH125.root Combine/
cp higgsCombineTest.AsymptoticLimits.2JetVBF.mH125.root Combine/
cp higgsCombineTest.AsymptoticLimits.Comb.mH125.root Combine/
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/ETau/CB/higgsCombineTest.AsymptoticLimits.0Jet.mH125.root Combine/higgsCombineTest.AsymptoticLimits.et1.mH125.root
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/ETau/CB/higgsCombineTest.AsymptoticLimits.1Jet.mH125.root Combine/higgsCombineTest.AsymptoticLimits.et2.mH125.root
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/ETau/CB/higgsCombineTest.AsymptoticLimits.2JetGG.mH125.root Combine/higgsCombineTest.AsymptoticLimits.et3.mH125.root
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/ETau/CB/higgsCombineTest.AsymptoticLimits.2JetVBF.mH125.root Combine/higgsCombineTest.AsymptoticLimits.et4.mH125.root
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/EMu/CB/higgsCombineTest.AsymptoticLimits.0Jet.mH125.root Combine/higgsCombineTest.AsymptoticLimits.em1.mH125.root
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/EMu/CB/higgsCombineTest.AsymptoticLimits.1Jet.mH125.root Combine/higgsCombineTest.AsymptoticLimits.em2.mH125.root
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/EMu/CB/higgsCombineTest.AsymptoticLimits.2JetGG.mH125.root Combine/higgsCombineTest.AsymptoticLimits.em3.mH125.root
cp ~/CMSSW_10_2_15/src/CombineHarvester/CombineTools/FullRunII/EMu/CB/higgsCombineTest.AsymptoticLimits.2JetVBF.mH125.root Combine/higgsCombineTest.AsymptoticLimits.em4.mH125.root
